services:
  web:
    build:
      context: /home/diego/proyecto_web/docker/proyecto_react/
      dockerfile: ./dockerfiles/nginx/dockerfile
    container_name: ctspotify
    ports:
      - "${PORT_WEB}:80"     
    env_file:
      - ./.env
    image: dmorrid/nginx
    volumes:
      - ../../pproyecto/dist:/var/www/html
      - ./logs:/root/logs      
    networks:
      netmegacrossover:
        ipv4_address: ${IP}
networks:
  netmegacrossover:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}