services:
  web:
    image: deploy-web
    build:
      context: ../../..
      dockerfile: dockerfiles/nginx/dockerfile
    ports:
      - "6969:80"     
    volumes:
      - ./logs:/root/logs      
    networks:
      netmegacrossovernginx:
        ipv4_address: 172.120.7.4
networks:
  netmegacrossovernginx:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.120.7.0/24