services:
  web:
    build:
      context: /home/diego/proyecto_web/docker/proyecto_react/
      dockerfile: ./dockerfiles/ubbase/dockerfile
    container_name: ctspotify
    image: dmorrid/ubbase
    ports:
      - ${PORT_SSH}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      netproyecto_web:
        ipv4_address: ${IP_WEB}
networks:
  netproyecto_web:
    name: netproyecto_web
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
