version: '3.8'

services:
  pftp:
    build:
      context: ../../../dockerfiles/pftp
      dockerfile: Dockerfile
    image: diego/pftp
    container_name: pftp
    ports:
      - "${FTP_PORT}:21"
      - "${GUI_PORT}:8080"
      - "${PASV_MIN_PORT}-${PASV_MAX_PORT}:${PASV_MIN_PORT}-${PASV_MAX_PORT}"
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - GUI_PORT=${GUI_PORT}
    volumes:
      - ftp_data:/home/ftpusers
    restart: unless-stopped
    networks:
      netproyecto_web:
        ipv4_address: ${IP_PFTP}

networks:
  netproyecto_web:
    name: netproyecto_web
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

volumes:
  ftp_data:
