version: '3.8'

services:
  pftp:
    build:
      context: ./dockerfiles/pftp/dockerfile
      dockerfile: Dockerfile
    image: dmorrid/pftp
    container_name: pftp
    ports:
      - "${FTP_PORT}:21"
      - "${GUI_PORT}:8000"
      - "${PASV_MIN_PORT}-${PASV_MAX_PORT}:${PASV_MIN_PORT}-${PASV_MAX_PORT}"
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - GUI_PORT=${GUI_PORT}
      - PASV_MIN_PORT=${PASV_MIN_PORT}
      - PASV_MAX_PORT=${PASV_MAX_PORT}
      - FTP_PUBLIC_IP=${FTP_PUBLIC_IP}
    volumes:
      - ftp_data:/home/ftpusers
    restart: unless-stopped
    networks:
      netproyecto_ftp:
        ipv4_address: ${IP_PFTP}

networks:
  netproyecto_ftp:
    name: netproyecto_ftp
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

volumes:
  ftp_data:
