apiVersion: v1
kind: Service
metadata:
  name: webspotify-service
  namespace: pspotify
spec:
  type: NodePort
  selector:
    app: webspotify
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081