services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/ubsecurity/dockerfile
    cap_add:
      - NET_ADMIN
    container_name: ${CONTAINER_NAME}
    image: diego/ubsecurity
    ports:
      - ${PORT_SSH}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs 
    networks:
      netproyecto_web:
        ipv4_address: ${IP_WEB}
networks:
  netproyecto_web:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}