services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/node/node
    container_name: ${NOMBRE}
    ports:
      - "80:80"   
      - "443:443"  
    env_file:
      - ./.env
    image: diego/nodejs
    volumes:
      - ./logs:/root/logs      
      - ../pproyecto:/root/admin/node/proyecto/pproyecto
    networks:
      netmegacrossovernode:
        ipv4_address: ${IP}
networks:
  netmegacrossovernode:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}