services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/pspotify/dockerfile
    container_name: ${NOMBRE}
    ports:
      - "${PORT_WEB}:80"    
    env_file:
      - ./.env
    image: diego/spotify
    volumes:
      - ./logs:/root/logs      
    networks:
      netmegacrossovernode:
        ipv4_address: ${IP}
networks:
  netmegacrossovernode:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}