services:
  web:
    build:
      context: /home/diego/proyecto_web/docker/proyecto_react/
      dockerfile: ./dockerfiles/pspotify/dockerfile
    container_name: ctspotify
    ports:
      - "${PORT_WEB}:80"    
    env_file:
      - ./.env
    image: dmorrid/spotify
    volumes:
      - ./logs:/root/logs      
    networks:
      netmegacrossovernode:
        ipv4_address: ${IP}
networks:
  netmegacrossovernode:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}